version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped
